/** One characteristic snippet per known language (tests only). */
export const LANGUAGE_SAMPLES: Record<string, string> = {
  javascript: "const express = require('express');\nconst app = express();\napp.get('/', (req, res) => res.send('ok'));",
  typescript: "import { readFile } from 'fs/promises';\ninterface Row { id: string }\nexport async function load(path: string): Promise<Row[]> {\n  return JSON.parse(await readFile(path, 'utf8'));\n}",
  python: 'import requests\n\ndef load(url):\n    return requests.get(url).json()\n',
  java: 'package com.acme;\n\nimport java.util.List;\n\npublic class Greeter {\n    @Override\n    public String toString() { return "x"; }\n}',
  csharp: 'using System;\n\npublic class Greeter\n{\n    public string Name { get; set; }\n    public void Hello() => Console.WriteLine(Name);\n}',
  cpp: '#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> v{1, 2};\n    std::cout << v.size() << std::endl;\n}',
  c: '#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    char *buf = malloc(16);\n    printf("%s\\n", buf);\n    free(buf);\n    return 0;\n}',
  go: 'package main\n\nimport "fmt"\n\nfunc main() {\n    name := "x"\n    fmt.Println(name)\n}',
  rust: 'use std::collections::HashMap;\n\nfn main() {\n    let mut seen = HashMap::new();\n    println!("{:?}", seen);\n}',
  php: '<?php\nclass Customer {\n    private $name;\n    public function getName() { return $this->name; }\n}',
  kotlin: 'data class Customer(val name: String)\n\nfun greet(c: Customer) {\n    println("Hello ${c.name}")\n}',
  swift: 'import SwiftUI\n\nstruct ContentView: View {\n    var body: some View {\n        Text("Hello")\n    }\n}',
  ruby: "require 'json'\n\nclass Order\n  def total\n    items.sum { |i| i.price }\n  end\nend\n\nputs Order.new.total",
  sql: 'SELECT c.name, COUNT(o.id)\nFROM customers c\nJOIN orders o ON o.customer_id = c.id\nWHERE c.active = 1\nGROUP BY c.name;',
  bash: '#!/usr/bin/env bash\nset -euo pipefail\nfor f in *.log; do\n  echo "$f"\ndone\nif [[ -z "${HOME:-}" ]]; then\n  exit 1\nfi',
  powershell: 'param([string]$Path)\n$files = Get-ChildItem -Path $Path -Recurse\nforeach ($f in $files) {\n    Write-Host $f.Name\n}',
  r: 'library(dplyr)\ndf <- read.csv("orders.csv")\nsummary <- df %>% group_by(region) %>% summarise(total = sum(amount))\nprint(summary)',
  dart: "import 'package:flutter/material.dart';\n\nclass MyApp extends StatelessWidget {\n  @override\n  Widget build(BuildContext context) {\n    return Text('hi');\n  }\n}",
  scala: 'object Main extends App {\n  case class Order(id: Int, total: Double)\n  def sum(xs: List[Order]): Double = xs.map(_.total).sum\n  println(sum(Nil))\n}',
  lua: 'local function greet(name)\n  print("Hello " .. name)\nend\n\nfor i, v in ipairs(items) do\n  greet(v)\nend',
  perl: '#!/usr/bin/perl\nuse strict;\nuse warnings;\n\nmy @items = (1, 2, 3);\nforeach my $item (@items) {\n    print "$item\\n";\n}',
  haskell: 'module Main where\n\nimport Data.List (sort)\n\nmain :: IO ()\nmain = print (sort [3, 1, 2])',
  elixir: 'defmodule Greeter do\n  def hello(name) do\n    name |> String.upcase() |> IO.puts()\n  end\nend',
  erlang: '-module(hello).\n-export([start/0]).\n\nstart() ->\n    io:format("Hello~n").',
  julia: 'using LinearAlgebra\n\nfunction total(xs::Vector{Float64})\n    return sum(xs)\nend\n\nprintln(total([1.0, 2.0]))',
  objectivec: '#import <Foundation/Foundation.h>\n\n@interface Greeter : NSObject\n@property (nonatomic, strong) NSString *name;\n@end',
  vbnet: 'Imports System\n\nModule Program\n    Sub Main()\n        Dim name As String = "x"\n        Console.WriteLine(name)\n    End Sub\nEnd Module',
  fsharp: 'open System\n\nlet square x = x * x\nlet numbers = [ for i in 1..10 -> square i ]\nprintfn "%A" numbers',
  groovy: "apply plugin: 'java'\n\ndependencies {\n    implementation 'org.slf4j:slf4j-api:2.0.9'\n}\n\ndef greet = { name -> println \"Hello $name\" }",
  clojure: '(ns example.core\n  (:require [clojure.string :as str]))\n\n(defn greet [name]\n  (str/upper-case name))',
  ocaml: 'let rec fact n = if n <= 1 then 1 else n * fact (n - 1)\n\nlet () = Printf.printf "%d\\n" (fact 5)',
  matlab: 'function [m, s] = stats(x)\n    m = mean(x);\n    s = std(x);\n    disp(m);\nend',
  fortran: 'program hello\n    implicit none\n    integer :: i\n    do i = 1, 3\n        print *, i\n    end do\nend program hello',
  delphi: "program Hello;\n\nvar\n  Name: string;\nbegin\n  Name := 'World';\n  WriteLn('Hello ', Name);\nend.",
  x86asm: 'section .text\nglobal _start\n_start:\n    mov eax, 1\n    xor ebx, ebx\n    int 0x80',
  ada: 'with Ada.Text_IO; use Ada.Text_IO;\n\nprocedure Hello is\nbegin\n   Put_Line ("Hello");\nend Hello;',
  lisp: '(defun square (x)\n  (* x x))\n\n(defvar *total* 0)\n(format t "~a~%" (square 3))',
  scheme: '(define (square x)\n  (* x x))\n\n(display (square 3))',
  prolog: 'parent(tom, bob).\nparent(bob, ann).\n\ngrandparent(X, Z) :- parent(X, Y), parent(Y, Z).',
  smalltalk: '| total |\ntotal := 0.\n#(1 2 3) do: [:each | total := total + each].\nTranscript show: total printString.',
  tcl: 'proc greet {name} {\n    puts "Hello $name"\n}\nset count [expr {1 + 2}]\ngreet World',
  vbscript: 'Dim fso\nSet fso = CreateObject("Scripting.FileSystemObject")\nWScript.Echo fso.GetFolder(".").Path',
  d: 'import std.stdio;\n\nvoid main() {\n    immutable name = "x";\n    writeln("Hello ", name);\n}',
  nim: 'proc greet(name: string): string =\n  result = "Hello " & name\n\necho greet("World")',
  crystal: 'def add(a : Int32, b : Int32) : Int32\n  a + b\nend\n\nputs add(1, 2)',
  elm: 'module Main exposing (main)\n\nimport Html exposing (text)\n\nmain =\n    text "Hello"',
  haxe: 'package;\n\nclass Main {\n    static function main():Void {\n        trace("Hello");\n    }\n}',
  coffeescript: 'square = (x) -> x * x\n\ngreet = (name) ->\n  console.log "Hello #{name}"\n\ngreet "World" unless done',
  vhdl: 'library ieee;\nuse ieee.std_logic_1164.all;\n\nentity blink is\n    port (clk : in std_logic);\nend blink;',
  verilog: 'module counter(input clk, output reg [3:0] q);\n    always @(posedge clk) begin\n        q <= q + 1;\n    end\nendmodule',
};
