import { grammarNames, type CodeLanguage } from '../code-language';

/**
 * Official names per language and per library profile, for code renaming.
 * The JSON files next to this module are generated by
 * `scripts/build-code-lexicon.js` from offline, Apache-2.0 compatible
 * sources and hold names only.
 *
 * A language lexicon applies to code detected as that language: the
 * language's generated standard-library names (JavaScript, Python, C#, Java,
 * Kotlin, Go, PHP, Ruby) merged with the keywords and built-ins of its
 * highlight.js grammar (all fifty languages). A profile
 * (jQuery, React, pandas, LINQ …) applies once its signals appear anywhere in
 * the paste — independently of the detected language, so a one-line
 * `$('.x').addClass('y')` activates jQuery. Data is loaded on first use:
 * only the activation signals are read up front.
 */

export interface LexiconData {
  id: string;
  languages: CodeLanguage[];
  sources: string[];
  /** Standalone values and functions (`console`, `useState`, `$`). */
  globals: string[];
  /** Standalone type names (`HTMLElement`, `DataFrame`). */
  types: string[];
  /** Names that are the library's only as a receiver (`np.`, `path.`, `os.`). */
  namespaces: string[];
  /** Members per owner: a global's static members or a type's instance members. */
  members: Record<string, string[]>;
  /** Owners whose members are recognised on any receiver (`rows.filter`, `df.groupby`). */
  valueTypes: string[];
  /** Owners whose members are option keys (`$.ajax({ url })`, `requests.get(u, timeout=5)`). */
  optionTypes: string[];
}

type Signal = string | { all: string[] };

interface SignalsFile {
  profiles: Record<string, { languages: CodeLanguage[]; signals: Signal[] }>;
}

export class Lexicon {
  readonly id: string;
  readonly languages: ReadonlySet<CodeLanguage>;
  /** Globals and types: official wherever they stand. */
  readonly names: ReadonlySet<string>;
  readonly namespaces: ReadonlySet<string>;
  /** Members of the value types: official after any receiver. */
  readonly valueMembers: ReadonlySet<string>;
  readonly optionKeys: ReadonlySet<string>;
  readonly members: ReadonlyMap<string, ReadonlySet<string>>;

  constructor(data: LexiconData, extraNames: readonly string[] = []) {
    this.id = data.id;
    this.languages = new Set(data.languages);
    this.names = new Set([...data.globals, ...data.types, ...extraNames]);
    this.namespaces = new Set(data.namespaces);
    this.members = new Map(Object.entries(data.members).map(([owner, names]) => [owner, new Set(names)]));
    this.valueMembers = new Set(data.valueTypes.flatMap((owner) => data.members[owner] ?? []));
    this.optionKeys = new Set(data.optionTypes.flatMap((owner) => data.members[owner] ?? []));
  }

  /** Whether the lexicon applies to code of `language` (`unknown` admits every lexicon). */
  appliesTo(language: CodeLanguage): boolean {
    return language === 'unknown' || this.languages.has(language);
  }
}

// Loaded on first use (`require` keeps the JSON out of startup work).
const LANGUAGE_DATA: Partial<Record<CodeLanguage, () => LexiconData>> = {
  javascript: () => require('./javascript.json'),
  typescript: () => require('./javascript.json'),
  coffeescript: () => require('./javascript.json'),
  python: () => require('./python.json'),
  csharp: () => require('./csharp.json'),
  java: () => require('./java.json'),
  groovy: () => require('./java.json'),
  kotlin: () => require('./kotlin.json'),
  go: () => require('./go.json'),
  php: () => require('./php.json'),
  ruby: () => require('./ruby.json'),
};

const PROFILE_DATA: Record<string, () => LexiconData> = {
  angular: () => require('./profiles/angular.json'),
  aspnetcore: () => require('./profiles/aspnetcore.json'),
  django: () => require('./profiles/django.json'),
  efcore: () => require('./profiles/efcore.json'),
  express: () => require('./profiles/express.json'),
  jquery: () => require('./profiles/jquery.json'),
  junit: () => require('./profiles/junit.json'),
  linq: () => require('./profiles/linq.json'),
  lodash: () => require('./profiles/lodash.json'),
  node: () => require('./profiles/node.json'),
  numpy: () => require('./profiles/numpy.json'),
  pandas: () => require('./profiles/pandas.json'),
  react: () => require('./profiles/react.json'),
  requests: () => require('./profiles/requests.json'),
  rxjs: () => require('./profiles/rxjs.json'),
  spring: () => require('./profiles/spring.json'),
  vue: () => require('./profiles/vue.json'),
};

const loadSignals = (): SignalsFile => require('./profile-signals.json');

export const PROFILE_IDS: readonly string[] = Object.keys(PROFILE_DATA);

const lexicons = new Map<string, Lexicon>();

function cached(key: string, load: () => LexiconData): Lexicon {
  let lexicon = lexicons.get(key);
  if (!lexicon) {
    lexicon = new Lexicon(load());
    lexicons.set(key, lexicon);
  }
  return lexicon;
}

const EMPTY: Omit<LexiconData, 'id' | 'languages'> = { sources: [], globals: [], types: [], namespaces: [], members: {}, valueTypes: [], optionTypes: [] };

/**
 * The official names of `language`: its generated lexicon, when there is
 * one, plus its grammar's keywords and built-ins. `unknown` has none.
 */
export function languageLexicon(language: CodeLanguage): Lexicon | undefined {
  if (language === 'unknown') return undefined;
  let lexicon = lexicons.get(`language:${language}`);
  if (!lexicon) {
    const grammar = grammarNames(language);
    const data = LANGUAGE_DATA[language]?.() ?? { id: language, languages: [language], ...EMPTY };
    // C#'s grammar keywords include contextual ones (`value`, `file`, `args`, `select`) that are everyday identifiers.
    const grammarWords = grammar ? [...(language === 'csharp' ? [] : grammar.keywords), ...grammar.builtIns] : [];
    lexicon = new Lexicon({ ...data, id: language, languages: [language] }, grammarWords);
    lexicons.set(`language:${language}`, lexicon);
  }
  return lexicon;
}

export function profileLexicon(id: string): Lexicon {
  const load = PROFILE_DATA[id];
  if (!load) throw new Error(`Unknown code lexicon profile: ${id}`);
  return cached(`profile:${id}`, load);
}

let compiledSignals: Array<{ id: string; tests: RegExp[][] }> | undefined;

function signals(): Array<{ id: string; tests: RegExp[][] }> {
  if (!compiledSignals) {
    compiledSignals = Object.entries(loadSignals().profiles).map(([id, profile]) => ({
      id,
      tests: profile.signals.map((signal) =>
        (typeof signal === 'string' ? [signal] : signal.all).map((pattern) => new RegExp(pattern, 'm')),
      ),
    }));
  }
  return compiledSignals;
}

/** Ids of the profiles whose signals appear in `code`. */
export function detectProfiles(code: string): string[] {
  if (code.trim() === '') return [];
  return signals()
    .filter((profile) => profile.tests.some((all) => all.every((pattern) => pattern.test(code))))
    .map((profile) => profile.id);
}

/** The profiles whose signals appear in `code`, loaded. */
export function activeProfiles(code: string): Lexicon[] {
  return detectProfiles(code).map(profileLexicon);
}
